name: Full Stack CI

on:
  push:
    branches:
      - main
      - 'ci*'
  pull_request:
    branches:
      - main
      - 'ci*'

jobs:
  test-api-linux:
    name: API Test (Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: ls -l api/package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            api/package-lock.json
      - run: npm ci
      - run: npm test

  test-frontend-linux:
    name: Frontend Test (Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: ls -l frontend/package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
      - run: npm ci
      - run: npm test

  test-api-windows:
    name: API Test (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: dir api\package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            api/package-lock.json
      - run: npm ci
      - run: npm test

  test-frontend-windows:
    name: Frontend Test (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: dir frontend\package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
      - run: npm ci
      - run: npm test
