name: Full Stack CI

on:
  push:
    branches:
      - main
      - 'ci*'
      - 'front-end'
      - 'api'
  pull_request:
    branches:
      - main
      - 'ci*'
      - 'front-end'
      - 'api'

jobs:
  test-api-linux:
    name: API Test (Linux)
    if: github.ref_name == 'api' || (github.ref_name != 'api' && github.ref_name != 'front-end')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: ls -l api/package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      - run: npm ci
        working-directory: api
      - run: npm test
        working-directory: api

  test-frontend-linux:
    name: Frontend Test (Linux)
    if: github.ref_name == 'front-end' || (github.ref_name != 'api' && github.ref_name != 'front-end')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: ls -l front-end/package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json
      - run: npm ci
        working-directory: front-end
      - run: npm test
        working-directory: front-end

  test-api-windows:
    name: API Test (Windows)
    if: github.ref_name == 'api' || (github.ref_name != 'api' && github.ref_name != 'front-end')
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: dir api\package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      - run: npm ci
        working-directory: api
      - run: npm test
        working-directory: api

  test-frontend-windows:
    name: Frontend Test (Windows)
    if: github.ref_name == 'front-end' || (github.ref_name != 'api' && github.ref_name != 'front-end')
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - run: dir front-end\package-lock.json
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json
      - run: npm ci
        working-directory: front-end
      - run: npm test
        working-directory: front-end
